# Generated by Django 3.0.4 on 2020-03-24 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200324_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='previous_next',
            new_name='next_post',
        ),
    ]
