# Generated by Django 3.0.4 on 2020-03-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marketing',
            new_name='Signup',
        ),
    ]
